name: abdc-gcloud
on:
  push:
    branches: [main]
env:
  CLOUD_RUN_SERVICE_ACCOUNT_EMAIL: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  CLOUD_RUN_PROJECT_ID: abdc-gmb
  CLOUD_RUN_REGION: europe-west1
  IMAGE_NAME: gcr-test
  SERVICE_NAME: gcr-test
  BIGBOSS: oussams93

jobs:
  build-and-deploy-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Set-up env file
        run: |-
          BIGBOSS=${{ env.BIGBOSS }}

      - name: Build and tag image
        run: |-
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:v0.0.1
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$IMAGE_NAME:v0.0.1

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.CLOUD_RUN_PROJECT_ID }}/${{ env.IMAGE_NAME }}:v0.0.1
          region: ${{ env.CLOUD_RUN_REGION }}
          flags: '--allow-unauthenticated'
